### PR TITLE
Add matplotlib to list of dependencies

### PR DESCRIPTION
**Pull request by mwcraig**
`wcsaxes` fails on import if `matplotlib` isn't installed, but `matplotlib` is not listed as a dependency. This adds it...let me know if you want it listed in both `requires` and `install_requires`.

The issue was noticed as part of an effort to automatically build conda packages for astropy affiliated packages.

### CODE REVIEW

**Comment by astrofrog** [comment]
Thanks! According to @embray [0], ``requires`` should be simply removed, so could you remove that line? (the install_requires one looks fine now)

[0] https://groups.google.com/forum/#!topic/astropy-dev/urYO8ckB2uM

**Comment by astrofrog** [comment]
Failure is unrelated. Thanks for the PR!

**Comment by astrofrog** [comment]
@mwcraig - do I need to do a new release before you can do a conda package?

**Comment by mwcraig** [comment]
@astrofrog -- how about instead we use this as a testing opportunity? I'll put in a temporary recipe for wcsaxes, when that has been built you can do a new release.

Then we can check a few things:

+ Does the notification that I'm hoping happens through gemnasium.com actually happen when a new version is released?
+ How clear are the instructions for the PR to make when a new version is released to get that version built?
+ Does the build/upload happen from a PR as I'm hoping?

**Comment by astrofrog** [comment]
@mwcraig - ok, sounds good! Let me know when you are ready for me to try releasing :)

**Pull request merged**
