### PR TITLE
Methods for setting tick/tick label visibility

### LINKED ISSUE #169: Expose CoordinateHelper.ticklabels (for those wanting to hide ticklabels)
I've been using wcsaxes to make figures with a `GridSpec` of axes that show the same patch of sky, but with different images and patch distributions in each, etc.. To make the plot compact, I needed to hide the tick labels of any axis that butted up to a neighbour. The solution is simple:

```
ax.coords[i].ticklabels.set_visible(False)
```

but the problem is to figure out this was possible I had to go through the source to find out that the `coords` attribute provided a ``CoordinateHelper``, which had an undocumented attribute ``ticklabels`` that I could then treat with the usual matplotlib methods. I think what I'm doing is such a potentially common use case that perhaps it should be exposed more clearly. I see a few things that could be done:

1. Update the documentation at http://wcsaxes.readthedocs.org/en/latest/ticks_labels_grid.html with a small section on hiding ``ticklabels`` using the above method call.
2. Document the ``ticklabels`` attribute of ``CoordinateHelper``.
3. Add a method to ``CoordinateHelper`` called ``set_ticklabels_visible()``, or something like that, as a convenience.

I think 1 & 2 would be a great idea. Implementing 3 would depend on whether your want to expand the API in this direction. Let me know what you think would be good and I can make a PR.

### PR DESCRIPTION
**Pull request by jonathansick**
Add `set_ticks_visible` and `set_ticklabel_visible` methods to toggle tick and tick label visibility. Includes a new section in the ticks/tick label documentation page.

Fixes #169.

### CODE REVIEW

**Comment by astrofrog** [comment]
@jonathansick - could you rebase? I think the issues in Travis have been fixed, but just want to be sure.

**Comment by jonathansick** [comment]
I've rebased. There is some issue with the sphinx build... possibly related my doc additions, or perhaps a phantom issue?

**Comment by anizami** [comment]
What's the issue with the sphinx build? I was able to build the docs from your branch successfully.

**Comment by astrofrog** [comment]
I restarted it, it was a network fluke. The coverage failure is real though ;) But I think I'll let @jonathansick off for this time.

**Comment by anizami** [comment]
-0.1%..wow.

**Comment by jonathansick** [comment]
I'm cool with adding tests :) Would I test against object state in matplotlib? Or would I test against plot appearance? You have a mpl testing package, right? I need to check it out.

**Comment by anizami** [comment]
You probably don't need to add a separate test for this. Just call these functions in any existing image test you think seems appropriate, and update the baseline images (unless @astrofrog suggests differently). Most of the tests for this package are done via image comparisons.

**Comment by astrofrog** [comment]
@jonathansick - cool, thanks! Yes there are image-based tests in ``test_image.py`` already, so you could just add one there or modify one.

Note that there is a slight annoyance for generating images at the moment which is that you need to comment out this line in ``setup.cfg``:

```
addopts = --mpl --mpl-baseline-path=wcsaxes/tests/baseline_images
```

before you can generate the images with:

```
py.test  --mpl-generate-path=tmp wcsaxes
```

Once baseline image looks good, move it to ``wcsaxes/tests/baseline_image``

I'll fix in a new version of pytest-mpl soon

**Comment by astrofrog** [comment]
Thinking about this a bit, since the diff will contain a full new image anyway, I don't think there's any hard in adding a new test for this rather than modifying an existing one.

**Comment by astrofrog** [comment]
I'm going to go ahead and merge this, and we can always add a test later.

**Comment by astrofrog** [comment]
Thanks @jonathansick!

**Pull request merged**
