### PR TITLE
Bugfix issue 139

### PR DESCRIPTION
**Pull request by PBarmby**
Addresses #139 by showing how to flip the horizontal axis of the same image used in the previous example.

### CODE REVIEW

**Comment by astrofrog** [comment]
Thanks! Just to check, does this work properly in practice? (it *should* but just want to make sure there are no bugs)

**Comment by PBarmby** [comment]
Yes, I just checked and it does work (whew!)

**Comment by astrofrog** [comment]
@PBarmby - I just discovered ``ax.invert_xaxis()`` - could you check to see if that works too, and if so, update this pull request?

**Comment by PBarmby** [comment]
Done!

**Comment by astrofrog** [comment]
@PBarmby - thanks! :)

**Pull request merged**
